from enum import IntEnum


class LoanConstants(IntEnum):
    LOAN_LENGTH_YEARS = 30
    REPAYMENT_THRESHOLD = 27_295

    MIN_OWABLE = 0
    MAX_OWABLE = 1_000_000
    DEFAULT_OWABLE = 50_000

    EARLIEST_GRADUATION_YEAR = 2012
    LATEST_GRADUATION_YEAR = 2022
    DEFAULT_GRADUATION_YEAR = 2020

    MIN_INTEREST_RATE_PERC = 0.1
    MAX_INTEREST_RATE_PERC = 10
    DEFAULT_INTEREST_RATE_PERC = 4.3


class SalaryConstants(IntEnum):
    MIN_SALARY = 0
    MAX_SALARY = 1_000_000
    DEFAULT_SALARY = 35_000

    MIN_GROWTH_RATE_PERC = 0
    MAX_GROWTH_RATE_PERC = 50
    DEFAULT_GROWTH_RATE_PERC = 5

    MIN_GROWTH_ANNEALING_RATE_PERC = 0
    MAX_GROWTH_ANNEALING_RATE_PERC = 100
    DEFAULT_GROWTH_ANNEALING_RATE_PERC = 90
