from dataclasses import dataclass


@dataclass(frozen=True)
class LoanConstants:
    LOAN_LENGTH_YEARS: int = 30
    REPAYMENT_THRESHOLD: int = 27_295

    MIN_OWABLE: int = 0
    MAX_OWABLE: int = 1_000_000
    DEFAULT_OWABLE: int = 50_000

    EARLIEST_GRADUATION_YEAR: int = 2012
    LATEST_GRADUATION_YEAR: int = 2022
    DEFAULT_GRADUATION_YEAR: int = 2020

    MIN_INTEREST_RATE_PERC: float = 0.1
    MAX_INTEREST_RATE_PERC: float = 10.0
    DEFAULT_INTEREST_RATE_PERC: float = 4.3

    MIN_REPAYMENT_PERCENTAGE_OVER_THRESHOLD: int = 9
    MAX_REPAYMENT_PERCENTAGE_OVER_THRESHOLD: int = 30
    DEFAULT_REPAYMENT_PERCENTAGE_OVER_THRESHOLD: int = 9

    MIN_LUMP_SUM_PAYMENT_TODAY: int = 0
    DEFAULT_LUMP_SUM_PAYMENT_TODAY: int = 0


@dataclass(frozen=True)
class SalaryConstants:
    MIN_SALARY: int = 0
    MAX_SALARY: int = 1_000_000
    DEFAULT_SALARY: int = 35_000

    MIN_GROWTH_RATE_PERC: int = 0
    MAX_GROWTH_RATE_PERC: int = 50
    DEFAULT_GROWTH_RATE_PERC: int = 5

    MIN_GROWTH_ANNEALING_RATE_PERC: int = 0
    MAX_GROWTH_ANNEALING_RATE_PERC: int = 100
    DEFAULT_GROWTH_ANNEALING_RATE_PERC: int = 90
